const ACTIONTYPES = {
    GET_USERS: 'GET_USERS',
    SET_PAGENO: 'SET_PAGENO',
    DECREMENT_PAGENO: 'DECREMENT_PAGENO',
    SELECT_USER: 'SELECT USER',
    CLEAR_USERSELECTION: 'CLEAR_USERSELECTION',
    POP_TOAST: 'POP_TOAST',
    START_SPINNING: 'START_SPINNING',
    STOP_SPINNING: 'STOP_SPINNING'
};

export default ACTIONTYPES;