const ACTIONTYPES = {
    GET_USERS: 'GET_USERS',
    INCREMENT_PAGENO: 'INCREMENT_PAGENO',
    DECREMENT_PAGENO: 'DECREMENT_PAGENO',
    SELECT_USER: 'SELECT USER',
    CLEAR_USERSELECTION: 'CLEAR_USERSELECTION'
};

export default ACTIONTYPES;